local NoOffenseRaidLoot, NoOffenseRaidLoot = ...

NoOffenseRaidLoot.items = {
  ["Band of the Inevitable"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = "70", ["note"] = ""},
  ["Band of Unanswered Prayers"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = "70", ["note"] = ""},
  ["Band of Unnatural Forces"] = {["bisFor"] = "Hunter, Sword Rogue, Dagger Rogue, Fury Warrior", ["gp"] = "70", ["note"] = ""},
  ["Belt of the Grand Crusader"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Bonescythe Ring"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = "70", ["note"] = ""},
  ["Boots of Displacement"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Brimstone Staff"] = {["bisFor"] = "", ["gp"] = "100", ["note"] = "caster dps/healing"},
  ["Claw of the Frost Wyrm"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "melee"},
  ["Claymore of Unholy Might"] = {["bisFor"] = "", ["gp"] = "100", ["note"] = "melee"},
  ["Cloak of Suturing"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = "30", ["note"] = ""},
  ["Cloak of the Necropolis"] = {["bisFor"] = "Mage, Warlock", ["gp"] = "30", ["note"] = ""},
  ["Cloak of the Scourge"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Corrupted Ashbringer"] = {["bisFor"] = "", ["gp"] = "100", ["note"] = "melee"},
  ["Cryptfiend Silk Cloak"] = {["bisFor"] = "Prot Warrior, Feral Druid", ["gp"] = "30", ["note"] = ""},
  ["Crystal Webbed Robe"] = {["bisFor"] = "Shadow Priest", ["gp"] = "60", ["note"] = ""},
  ["Death's Bargain"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = "healer"},
  ["Desecrated Belt"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Bindings"] = {["bisFor"] = "Holy Priest", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Boots"] = {["bisFor"] = "Resto Druid, Holy Pally, Hunter", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Bracers"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Breastplate"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Circlet"] = {["bisFor"] = "Holy Priest, Mage, Warlock", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Gauntlets"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Girdle"] = {["bisFor"] = "Resto Druid, Holy Pally, Hunter", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Gloves"] = {["bisFor"] = "Holy Priest", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Handguards"] = {["bisFor"] = "Resto Druid, Hunter", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Headpiece"] = {["bisFor"] = "Resto Druid, Holy Pally, Hunter", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Helmet"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Leggings"] = {["bisFor"] = "Holy Priest", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Legguards"] = {["bisFor"] = "Resto Druid, Hunter", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Legplates"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Pauldrons"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Robe"] = {["bisFor"] = "Holy Priest, Mage, Warlock", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Sabatons"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Sandals"] = {["bisFor"] = "Holy Priest, Warlock", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Shoulderpads"] = {["bisFor"] = "Holy Priest, Warlock", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Spaulders"] = {["bisFor"] = "Resto Druid, Holy Pally, Hunter", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Tunic"] = {["bisFor"] = "Resto Druid, Holy Pally, Hunter", ["gp"] = "60", ["note"] = ""},
  ["Desecrated Waistguard"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = "40", ["note"] = ""},
  ["Desecrated Wristguards"] = {["bisFor"] = "Resto Druid, Hunter", ["gp"] = "40", ["note"] = ""},
  ["Digested Hand of Power"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Doomfinger"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Eye of Dimunition"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = ""},
  ["Eye of the Dead"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = "80", ["note"] = ""},
  ["Fortitude of the Scourge"] = {["bisFor"] = "", ["gp"] = "", ["note"] = ""},
  ["Frostfire Ring"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Gem of Nerubis"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Gem of Trapped Innocents"] = {["bisFor"] = "Mage, Warlock", ["gp"] = "70", ["note"] = ""},
  ["Ghoul Skin Tunic"] = {["bisFor"] = "Feral Druid", ["gp"] = "60", ["note"] = ""},
  ["Girdle of Elemental Fury"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Girdle of the Mentor"] = {["bisFor"] = "Prot Warrior, Fury Warrior", ["gp"] = "40", ["note"] = ""},
  ["Glacial Headdress"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Glacial Mantle"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Gluth's Missing Collar"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Glyph of Deflection"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = ""},
  ["Gressil, Dawn of Ruin"] = {["bisFor"] = "Sword Rogue, Fury Warrior", ["gp"] = "80", ["note"] = "melee"},
  ["Hailstone Band"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Hammer of the Twisting Nether"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = "80", ["note"] = "healing"},
  ["Harbinger of Doom"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "melee"},
  ["Hatchet of Sundered Bone"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "melee"},
  ["Iblis, Blade of the Fallen Seraph"] = {["bisFor"] = "Sword Rogue", ["gp"] = "80", ["note"] = "melee"},
  ["Icebane Helm"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Icebane Pauldrons"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Icy Scale Coif"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Icy Scale Spaulders"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Idol of Longevity"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Kingsfall"] = {["bisFor"] = "Dagger Rogue", ["gp"] = "80", ["note"] = "melee"},
  ["Kiss of the Spider"] = {["bisFor"] = "Prot Warrior, Feral Druid, Sword Rogue, Dagger Rogue, Fury Warrior", ["gp"] = "80", ["note"] = ""},
  ["Leggings of Apocalypse"] = {["bisFor"] = "Feral Druid", ["gp"] = "60", ["note"] = ""},
  ["Leggings of Elemental Fury"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Leggings of Polarity"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = "60", ["note"] = ""},
  ["Leggings of the Grand Crusader"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Legplates of Carnage"] = {["bisFor"] = "Fury Warrior", ["gp"] = "60", ["note"] = ""},
  ["Libram of Light"] = {["bisFor"] = "Holy Pally", ["gp"] = "30", ["note"] = ""},
  ["Loatheb's Reflection"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = ""},
  ["Maexxna's Fang"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "melee"},
  ["Malice Stone Pendant"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Maul of the Redeemed Crusader"] = {["bisFor"] = "", ["gp"] = "100", ["note"] = "melee"},
  ["Midnight Haze"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "caster/healing"},
  ["Might of Menethil"] = {["bisFor"] = "Fury Warrior", ["gp"] = "100", ["note"] = "melee"},
  ["Might of the Scourge"] = {["bisFor"] = "", ["gp"] = "", ["note"] = ""},
  ["Misplaced Servo Arm"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "melee"},
  ["Necklace of Necropsy"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Necro-Knight's Garb"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Nerubian Slavemaker"] = {["bisFor"] = "Hunter", ["gp"] = "30", ["note"] = "Hunter"},
  ["Noth's Frigid Heart"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Pendant of Forgotten Names"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Plagueheart Ring"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Plated Abomination Ribcage"] = {["bisFor"] = "Fury Warrior", ["gp"] = "60", ["note"] = ""},
  ["Polar Helmet"] = {["bisFor"] = "", ["gp"] = "60", ["note"] = ""},
  ["Polar Shoulder Pads"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Power of the Scourge"] = {["bisFor"] = "", ["gp"] = "", ["note"] = ""},
  ["Preceptor's Hat"] = {["bisFor"] = "Shadow Priest", ["gp"] = "60", ["note"] = ""},
  ["Resilience of the Scourge"] = {["bisFor"] = "", ["gp"] = "", ["note"] = ""},
  ["Rime Covered Mantle"] = {["bisFor"] = "Shadow Priest, Mage", ["gp"] = "40", ["note"] = ""},
  ["Ring of Faith"] = {["bisFor"] = "Holy Priest", ["gp"] = "70", ["note"] = ""},
  ["Ring of Redemption"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Ring of Spiritual Fervor"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Ring of the Cryptstalker"] = {["bisFor"] = "Hunter", ["gp"] = "70", ["note"] = ""},
  ["Ring of the Dreadnaught"] = {["bisFor"] = "Prot Warrior", ["gp"] = "70", ["note"] = ""},
  ["Ring of the Dreamwalker"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Ring of the Eternal Flame"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Sadist's Collar"] = {["bisFor"] = "Prot Warrior", ["gp"] = "70", ["note"] = ""},
  ["Sapphiron's Left Eye"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = "30", ["note"] = ""},
  ["Sapphiron's Right Eye"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = "30", ["note"] = ""},
  ["Seal of the Damned"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Shield of Condemnation"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = "healer"},
  ["Shroud of Dominion"] = {["bisFor"] = "Sword Rogue, Dagger Rogue, Fury Warrior", ["gp"] = "30", ["note"] = ""},
  ["Signet of the Fallen Defender"] = {["bisFor"] = "Feral Druid", ["gp"] = "70", ["note"] = ""},
  ["Slayer's Crest"] = {["bisFor"] = "Hunter, Sword Rogue, Dagger Rogue, Fury Warrior", ["gp"] = "80", ["note"] = ""},
  ["Soulseeker"] = {["bisFor"] = "", ["gp"] = "100", ["note"] = "caster dps"},
  ["Soulstring"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = "tanking/melee"},
  ["Spaulders of the Grand Crusader"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["Spire of Twilight"] = {["bisFor"] = "", ["gp"] = "100", ["note"] = "healing"},
  ["Stormrage's Talisman of Seething"] = {["bisFor"] = "Fury Warrior", ["gp"] = "70", ["note"] = ""},
  ["Stygian Buckler"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "tank"},
  ["The Castigator"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "melee"},
  ["The End of Dreams"] = {["bisFor"] = "Shadow Priest", ["gp"] = "80", ["note"] = "caster/healing/feral"},
  ["The Eye of Nerub"] = {["bisFor"] = "Hunter", ["gp"] = "100", ["note"] = "hunter"},
  ["The Face of Death"] = {["bisFor"] = "Prot Warrior", ["gp"] = "80", ["note"] = "tank"},
  ["The Hungering Cold"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Fury Warrior", ["gp"] = "80", ["note"] = "tanking/melee"},
  ["The Phylactery of Kel'Thuzad"] = {["bisFor"] = "Prot Warrior, Feral Druid, Shadow Priest, Mage, Warlock, Hunter, Sword Rogue, Dagger Rogue, Fury Warrior", ["gp"] = "80", ["note"] = ""},
  ["The Restrained Essence of Sapphiron"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = "80", ["note"] = ""},
  ["The Soul Harvester's Bindings"] = {["bisFor"] = "", ["gp"] = "40", ["note"] = ""},
  ["The Widow's Embrace"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "healing"},
  ["Touch of Frost"] = {["bisFor"] = "", ["gp"] = "70", ["note"] = ""},
  ["Toxin Injector"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = "tanking/melee"},
  ["Veil of Eclipse"] = {["bisFor"] = "", ["gp"] = "30", ["note"] = ""},
  ["Wand of Fates"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = "30", ["note"] = ""},
  ["Wand of the Whispering Dead"] = {["bisFor"] = "Holy Priest", ["gp"] = "30", ["note"] = ""},
  ["Warmth of Forgiveness"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = ""},
  ["Widow's Remorse"] = {["bisFor"] = "", ["gp"] = "80", ["note"] = "tanking/melee"},
  ["Wraith Blade"] = {["bisFor"] = "Mage, Warlock", ["gp"] = "80", ["note"] = "caster dps/healing"},
  ["Wristguards of Vengeance"] = {["bisFor"] = "Prot Warrior, Fury Warrior", ["gp"] = "40", ["note"] = ""}
}
