local NoOffenseRaidLoot, NoOffenseRaidLoot = ...

NoOffenseRaidLoot.items = {
  ["Aegis of Preservation"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Aged Core Leather Gloves"] = {["bisFor"] = "Dagger Rogue", ["gp"] = 40, ["note"] = ""},
  ["Amberseal Keeper"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Ancient Cornerstone Grimoire"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Ancient Petrified Leaf"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Angelista's Grasp"] = {["bisFor"] = "Warlock", ["gp"] = 40, ["note"] = ""},
  ["Arcane Infused Gem"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Arcanist Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Arcanist Bindings"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Arcanist Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Arcanist Crown"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Arcanist Gloves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Arcanist Leggings"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Arcanist Mantle"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Arcanist Robes"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Archimtiros' Ring of Reckoning"] = {["bisFor"] = "Prot Warrior, Feral Druid", ["gp"] = 70, ["note"] = ""},
  ["Ashjre'thul, Crossbow of Smiting"] = {["bisFor"] = "Hunter", ["gp"] = 80, ["note"] = ""},
  ["Ashkandi, Greatsword of the Brotherhood"] = {["bisFor"] = "Ret Pally, Hunter (2), Fury Warrior (3)", ["gp"] = 100, ["note"] = ""},
  ["Aurastone Hammer"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Azuresong Mageblade"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Band of Accuria"] = {["bisFor"] = "Prot Warrior, Sword Rogue (2), Dagger Rogue (2), Fury Warrior (2), Hunter (3)", ["gp"] = 70, ["note"] = ""},
  ["Band of Dark Dominion"] = {["bisFor"] = "Shadow Priest, Warlock", ["gp"] = 70, ["note"] = ""},
  ["Band of Forced Concentration"] = {["bisFor"] = "Mage, Warlock", ["gp"] = 70, ["note"] = ""},
  ["Band of Sulfuras"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Belt of Might"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Belt of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 40, ["note"] = ""},
  ["Bindings of the Windseeker"] = {["bisFor"] = "Prot Warrior", ["gp"] = 80, ["note"] = "Tank priority (handed out on seniority and current raiding situations) "},
  ["Bindings of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 40, ["note"] = ""},
  ["Black Ash Robe"] = {["bisFor"] = "Feral Druid", ["gp"] = 60, ["note"] = ""},
  ["Black Brood Pauldrons"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Blacklight Bracer"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Blastershot Launcher"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Blazefury Medallion"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Bloodfang Belt"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = 40, ["note"] = ""},
  ["Bloodfang Boots"] = {["bisFor"] = "Sword Rogue", ["gp"] = 40, ["note"] = ""},
  ["Bloodfang Bracers"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = 40, ["note"] = ""},
  ["Bloodfang Chestpiece"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = 60, ["note"] = ""},
  ["Bloodfang Gloves"] = {["bisFor"] = "Sword Rogue", ["gp"] = 40, ["note"] = ""},
  ["Bloodfang Hood"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = 60, ["note"] = ""},
  ["Bloodfang Pants"] = {["bisFor"] = "Sword Rogue, Dagger Rogue", ["gp"] = 60, ["note"] = ""},
  ["Bloodfang Spaulders"] = {["bisFor"] = "Sword Rogue", ["gp"] = 40, ["note"] = ""},
  ["Bonereaver's Edge"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Boots of Prophecy"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Boots of Pure Thought"] = {["bisFor"] = "Resto Druid, Holy Pally", ["gp"] = 40, ["note"] = ""},
  ["Boots of the Shadow Flame"] = {["bisFor"] = "Feral Druid, Sword Rogue (2), Dagger Rogue (2), Fury Warrior (3)", ["gp"] = 40, ["note"] = ""},
  ["Boots of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 40, ["note"] = ""},
  ["Bracelets of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 40, ["note"] = ""},
  ["Bracers of Arcane Accuracy"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = 40, ["note"] = ""},
  ["Bracers of Might"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Breastplate of Might"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Breastplate of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 60, ["note"] = ""},
  ["Brutality Blade"] = {["bisFor"] = "Fury Warrior, Prot Warrior (2)", ["gp"] = 80, ["note"] = "(Maladath is actually BIS for offhanding with TF according to Fight Club)"},
  ["Cauterizing Band"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = 70, ["note"] = ""},
  ["Cenarion Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Cenarion Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Cenarion Bracers"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Cenarion Gloves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Cenarion Helm"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Cenarion Leggings"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Cenarion Spaulders"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Cenarion Vestments"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Choker of Enlightenment"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Choker of the Fire Lord"] = {["bisFor"] = "Shadow Priest, Mage, Warlock, Holy Pally (2)", ["gp"] = 70, ["note"] = ""},
  ["Chromatic Boots"] = {["bisFor"] = "Prot Warrior, Fury Warrior, Ret Pally (2)", ["gp"] = 40, ["note"] = ""},
  ["Chromatically Tempered Sword"] = {["bisFor"] = "Sword Rogue, Fury Warrior", ["gp"] = 80, ["note"] = ""},
  ["Circle of Applied Force"] = {["bisFor"] = "Fury Warrior, Ret Pally (2), Feral Druid (3)", ["gp"] = 70, ["note"] = ""},
  ["Circlet of Prophecy"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Claw of Chromaggus"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Claw of the Black Drake"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Cloak of Draconic Might"] = {["bisFor"] = "Ret Pally, Fury Warrior", ["gp"] = 30, ["note"] = ""},
  ["Cloak of Firemaw"] = {["bisFor"] = "Sword Rogue, Dagger Rogue, Prot Warrior (2)", ["gp"] = 30, ["note"] = ""},
  ["Cloak of the Brood Lord"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Cloak of the Shrouded Mists"] = {["bisFor"] = "Hunter", ["gp"] = 30, ["note"] = ""},
  ["Cold Snap"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Core Forged Greaves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Core Hound Tooth"] = {["bisFor"] = "Dagger Rogue", ["gp"] = 80, ["note"] = ""},
  ["Crimson Shocker"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Crown of Destruction"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Crul'shorukh, Edge of Chaos"] = {["bisFor"] = "Fury Warrior", ["gp"] = 80, ["note"] = ""},
  ["Crystal Adorned Crown"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = 60, ["note"] = ""},
  ["Deathbringer"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Deep Earth Spaulders"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Doom's Edge"] = {["bisFor"] = "Fury Warrior", ["gp"] = 80, ["note"] = "non human BIS"},
  ["Doomhide Gauntlets"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Draconic Avenger"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Draconic Maul"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Dragon's Blood Cape"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Dragon's Touch"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Dragonbreath Hand Cannon"] = {["bisFor"] = "Prot Warrior", ["gp"] = 80, ["note"] = ""},
  ["Dragonfang Blade"] = {["bisFor"] = "Dagger Rogue", ["gp"] = 80, ["note"] = ""},
  ["Dragonstalker's Belt"] = {["bisFor"] = "Hunter", ["gp"] = 40, ["note"] = ""},
  ["Dragonstalker's Bracers"] = {["bisFor"] = "Hunter", ["gp"] = 40, ["note"] = ""},
  ["Dragonstalker's Breastplate"] = {["bisFor"] = "Hunter", ["gp"] = 60, ["note"] = ""},
  ["Dragonstalker's Gauntlets"] = {["bisFor"] = "Hunter", ["gp"] = 40, ["note"] = ""},
  ["Dragonstalker's Greaves"] = {["bisFor"] = "Hunter", ["gp"] = 40, ["note"] = ""},
  ["Dragonstalker's Helm"] = {["bisFor"] = "Hunter", ["gp"] = 60, ["note"] = ""},
  ["Dragonstalker's Legguards"] = {["bisFor"] = "Hunter", ["gp"] = 60, ["note"] = ""},
  ["Dragonstalker's Spaulders"] = {["bisFor"] = "Hunter", ["gp"] = 40, ["note"] = ""},
  ["Drake Fang Talisman"] = {["bisFor"] = "Prot Warrior, Feral Druid, Sword Rogue (2), Dagger Rogue (2), Fury Warrior (2), Ret Pally (3), Hunter (3)", ["gp"] = 80, ["note"] = "Tank, DPS, DPS (repeat)"},
  ["Drake Talon Cleaver"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Drake Talon Pauldrons"] = {["bisFor"] = "Prot Warrior, Fury Warrior, Ret Pally (2)", ["gp"] = 40, ["note"] = ""},
  ["Drape of Benediction"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Drillborer Disk"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Earthshaker"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Ebony Flame Gloves"] = {["bisFor"] = "Shadow Priest, Warlock", ["gp"] = 40, ["note"] = ""},
  ["Elementium Reinforced Bulwark"] = {["bisFor"] = "Prot Warrior", ["gp"] = 80, ["note"] = ""},
  ["Elementium Threaded Cloak"] = {["bisFor"] = "Prot Warrior, Feral Druid", ["gp"] = 30, ["note"] = ""},
  ["Emberweave Leggings"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Empowered Leggings"] = {["bisFor"] = "Holy Pally", ["gp"] = 60, ["note"] = ""},
  ["Empyrean Demolisher"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Eskhandar's Collar"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Eskhandar's Right Claw"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Eskhander's Left Claw"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Eskhander's Pelt"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Essence Gatherer"] = {["bisFor"] = "Holy Priest", ["gp"] = 30, ["note"] = ""},
  ["Essence of the Pure Flame"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Eye of Sulfuras"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = "whoever has the most matts gathered or wants to put in the effort to grind them"},
  ["Fang of the Mystics"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Fel Infused Leggings"] = {["bisFor"] = "Shadow Priest, Warlock", ["gp"] = 60, ["note"] = ""},
  ["Felheart Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Felheart Bracers"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Felheart Gloves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Felheart Horns"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Felheart Pants"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Felheart Robes"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Felheart Shoulder Pads"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Felheart Slippers"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Finkle's Lava Dredger"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Fire Runed Grimoire"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Fireguard Shoulders"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Firemaw's Clutch"] = {["bisFor"] = "Shadow Priest", ["gp"] = 40, ["note"] = ""},
  ["Fireproof Cloak"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Flameguard Gauntlets"] = {["bisFor"] = "Prot Warrior, Ret Pally", ["gp"] = 40, ["note"] = "Edgemasters > these gloves for appropriate races"},
  ["Flamewalker Legplates"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Flayed Doomguard Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Gauntlets of Might"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Gauntlets of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 40, ["note"] = ""},
  ["Giantstalker's Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Giantstalker's Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Giantstalker's Bracers"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Giantstalker's Breastplate"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Giantstalker's Epaulets"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Giantstalker's Gloves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Giantstalker's Helmet"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Giantstalker's Leggings"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Girdle of Prophecy"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Girdle of the Fallen Crusader"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Gloves of Prophecy"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Gloves of Rapid Evolution"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Gloves of the Hypnotic Flame"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Gutgore Ripper"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Halo of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 60, ["note"] = ""},
  ["Handguards of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 40, ["note"] = ""},
  ["Head of Nefarian"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue, Feral Druid (2), Ret Pally (2), Fury Warrior (2)", ["gp"] = 80, ["note"] = "Warrior tanks will most likely pick this up after hit rating is met to replace onyxia neck... so it may be a while"},
  ["Head of Onyxia"] = {["bisFor"] = "Prot Warrior, Ret Pally, Fury Warrior", ["gp"] = 80, ["note"] = ""},
  ["Head of the Broodlord Lashlayer"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = "post gong, whoever gets the biggest upgrade from quest and is willing to complete it"},
  ["Heartstriker"] = {["bisFor"] = "Fury Warrior", ["gp"] = 80, ["note"] = ""},
  ["Heavy Dark Iron Ring"] = {["bisFor"] = "Prot Warrior, Feral Druid", ["gp"] = 70, ["note"] = ""},
  ["Helm of Endless Rage"] = {["bisFor"] = "Prot Warrior", ["gp"] = 60, ["note"] = ""},
  ["Helm of Might"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Helm of the Lifegiver"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Helm of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 60, ["note"] = ""},
  ["Herald of Woe"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Infernal Headcage"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Interlaced Shadow Jerkin"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Judgement Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Judgement Bindings"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Judgement Breastplate"] = {["bisFor"] = "Ret Pally", ["gp"] = 60, ["note"] = ""},
  ["Judgement Crown"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Judgement Gauntlets"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Judgement Legplates"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Judgement Sabatons"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Judgement Spaulders"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Lawbringer Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Lawbringer Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Lawbringer Bracers"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Lawbringer Chestguard"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Lawbringer Gauntlets"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Lawbringer Helm"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Lawbringer Legplates"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Lawbringer Spaulders"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Leggings of Arcane Supremacy"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Leggings of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 60, ["note"] = ""},
  ["Legguards of the Fallen Crusader"] = {["bisFor"] = "Ret Pally, Fury Warrior", ["gp"] = 60, ["note"] = ""},
  ["Legplates of Might"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Legplates of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 60, ["note"] = ""},
  ["Lifegiving Gem"] = {["bisFor"] = "Prot Warrior", ["gp"] = 80, ["note"] = ""},
  ["Lok'amir il Romathis"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest, Shadow Priest", ["gp"] = 80, ["note"] = ""},
  ["Magma Tempered Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Maladath, Runed Blade of the Black Flight"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Fury Warrior", ["gp"] = 80, ["note"] = "Non-Human Prio for Fury warrior and Rogues"},
  ["Malfurion's Blessed Bulwark"] = {["bisFor"] = "Feral Druid, Fury Warrior (2)", ["gp"] = 60, ["note"] = ""},
  ["Malistar's Defender"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Mana Igniting Cord"] = {["bisFor"] = "Mage", ["gp"] = 40, ["note"] = ""},
  ["Manastorm Leggings"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Mantle of Prophecy"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Mantle of the Blackwing Cabal"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = 40, ["note"] = ""},
  ["Medallion of Steadfast Might"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Mind Quickening Gem"] = {["bisFor"] = "Mage", ["gp"] = 80, ["note"] = ""},
  ["Mish'undare, Circlet of the Mind Flayer"] = {["bisFor"] = "Mage, Warlock, Holy Pally (2)", ["gp"] = 60, ["note"] = ""},
  ["Neltharion's Tear"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = 80, ["note"] = ""},
  ["Nemesis Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nemesis Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nemesis Bracers"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nemesis Gloves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nemesis Leggings"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nemesis Robe"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nemesis Skullcap"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nemesis Spaulders"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Netherwind Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Netherwind Bindings"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Netherwind Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Netherwind Crown"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Netherwind Gloves"] = {["bisFor"] = "Mage", ["gp"] = 40, ["note"] = ""},
  ["Netherwind Mantle"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Netherwind Pants"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Netherwind Robes"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nightslayer Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nightslayer Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nightslayer Bracelets"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nightslayer Chestpiece"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nightslayer Cover"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nightslayer Gloves"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Nightslayer Pants"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Nightslayer Shoulder Pads"] = {["bisFor"] = "Dagger Rogue", ["gp"] = 40, ["note"] = ""},
  ["Obsidian Edged Blade"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Onslaught Girdle"] = {["bisFor"] = "Prot Warrior, Ret Pally, Fury Warrior", ["gp"] = 40, ["note"] = ""},
  ["Pants of Prophecy"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Pauldrons of Might"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Pauldrons of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 40, ["note"] = ""},
  ["Pauldrons of Wrath"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Pendant of the Fallen Dragon"] = {["bisFor"] = "Resto Druid", ["gp"] = 70, ["note"] = ""},
  ["Perdition's Blade"] = {["bisFor"] = "Dagger Rogue", ["gp"] = 80, ["note"] = ""},
  ["Prestor's Talisman of Connivery"] = {["bisFor"] = "Hunter, Sword Rogue, Dagger Rogue", ["gp"] = 70, ["note"] = ""},
  ["Primalist's Linked Leggaurds"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Primalist's Linked Waistguard"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Puissant Cape"] = {["bisFor"] = "Prot Warrior, Sword Rogue, Dagger Rogue, Fury Warrior", ["gp"] = 30, ["note"] = ""},
  ["Pure Elementium Band"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = 70, ["note"] = ""},
  ["Quick Strike Ring"] = {["bisFor"] = "Fury Warrior", ["gp"] = 70, ["note"] = ""},
  ["Red Dragonscale Protector"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Rejuvenating Gem"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = 80, ["note"] = ""},
  ["Ring of Binding"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Ring of Blackrock"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Ring of Entropy"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Ring of Spell Power"] = {["bisFor"] = "Mage", ["gp"] = 70, ["note"] = ""},
  ["Ringo's Blizzard Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Robe of Volatile Power"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Robes of Prophecy"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Robes of Transcendence"] = {["bisFor"] = "Holy Priest", ["gp"] = 60, ["note"] = ""},
  ["Rune of Metamorphosis"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Sabatons of Might"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Sabatons of the Flamewalker"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Sabatons of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 40, ["note"] = ""},
  ["Salamander Scale Pants"] = {["bisFor"] = "", ["gp"] = 60, ["note"] = ""},
  ["Sapphiron Drape"] = {["bisFor"] = "", ["gp"] = 30, ["note"] = ""},
  ["Sash of Whispered Secrets"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Scrolls of Blinding Light"] = {["bisFor"] = "Ret Pally", ["gp"] = 80, ["note"] = ""},
  ["Seal of the Archmagus"] = {["bisFor"] = "", ["gp"] = 70, ["note"] = ""},
  ["Shadow Wing Focus Staff"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Shadowstrike"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Shard of the Flame"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Shard of the Scale"] = {["bisFor"] = "Resto Druid, Holy Priest", ["gp"] = 80, ["note"] = ""},
  ["Shimmering Geta"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Shroud of Pure Thought"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = 30, ["note"] = ""},
  ["Snowblind Shoes"] = {["bisFor"] = "Shadow Priest", ["gp"] = 40, ["note"] = ""},
  ["Sorcerous Dagger"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Spinal Reaper"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Spineshatter"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Staff of Dominance"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Staff of the Shadow Flame"] = {["bisFor"] = "Mage, Warlock", ["gp"] = 100, ["note"] = ""},
  ["Stormrage Belt"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Stormrage Boots"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Stormrage Bracers"] = {["bisFor"] = "Resto Druid", ["gp"] = 40, ["note"] = ""},
  ["Stormrage Chestguard"] = {["bisFor"] = "Resto Druid", ["gp"] = 60, ["note"] = ""},
  ["Stormrage Cover"] = {["bisFor"] = "Resto Druid", ["gp"] = 60, ["note"] = ""},
  ["Stormrage Handguards"] = {["bisFor"] = "Resto Druid", ["gp"] = 40, ["note"] = ""},
  ["Stormrage Legguards"] = {["bisFor"] = "Resto Druid", ["gp"] = 60, ["note"] = ""},
  ["Stormrage Pauldrons"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Striker's Mark"] = {["bisFor"] = "Sword Rogue, Dagger Rogue, Fury Warrior, Prot Warrior (2)", ["gp"] = 80, ["note"] = ""},
  ["Styleen's Impeding Scarab"] = {["bisFor"] = "Prot Warrior", ["gp"] = 80, ["note"] = ""},
  ["Talisman of Ephemeral Power"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = 80, ["note"] = ""},
  ["Taut Dragonhide Belt"] = {["bisFor"] = "Feral Druid", ["gp"] = 40, ["note"] = ""},
  ["Taut Dragonhide Shoulderpads"] = {["bisFor"] = "Feral Druid", ["gp"] = 40, ["note"] = ""},
  ["The Black Book"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["The Eye of Divinity"] = {["bisFor"] = "Holy Priest", ["gp"] = 100, ["note"] = ""},
  ["The Untamed Blade"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Therazane's Link"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Typhoon"] = {["bisFor"] = "", ["gp"] = 100, ["note"] = ""},
  ["Unmelting Ice Girdle"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Vambraces of Prophecy"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Venomous Totem"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Vis'kag the Bloodletter"] = {["bisFor"] = "", ["gp"] = 80, ["note"] = ""},
  ["Waistband of Wrath"] = {["bisFor"] = "Prot Warrior", ["gp"] = 40, ["note"] = ""},
  ["Wild Growth Spaulders"] = {["bisFor"] = "Resto Druid, Holy Pally", ["gp"] = 40, ["note"] = ""},
  ["Wristguards of Stability"] = {["bisFor"] = "Feral Druid, Fury Warrior, Ret Pally (2)", ["gp"] = 40, ["note"] = ""},
  ["Wristguards of True Flight"] = {["bisFor"] = "", ["gp"] = 40, ["note"] = ""},
  ["Aegis of the Blood God"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Ancient Hakkari Manslayer"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Animist's Boots"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Animist's Leggings"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Animist's Spaulders"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Arlokk's Grasp"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Arlokk's Hoodoo Stick"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Band of Jin"] = {["bisFor"] = "Hunter", ["gp"] = 0, ["note"] = ""},
  ["Band of Servitude"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Belt of Untapped Power"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Betrayer's Boots"] = {["bisFor"] = "Shadow Priest", ["gp"] = 0, ["note"] = ""},
  ["Bloodcaller"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Blooddrenched Footpads"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Blooddrenched Grips"] = {["bisFor"] = "Feral Druid", ["gp"] = 0, ["note"] = ""},
  ["Blooddrenched Leggings"] = {["bisFor"] = "Feral Druid", ["gp"] = 0, ["note"] = ""},
  ["Blooddrenched Mask"] = {["bisFor"] = "Feral Druid", ["gp"] = 0, ["note"] = ""},
  ["Bloodlords Defender"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodsoaked Gauntlets"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodsoaked Greaves"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodsoaked Legplates"] = {["bisFor"] = "Prot Warrior", ["gp"] = 0, ["note"] = ""},
  ["Bloodsoaked Pauldrons"] = {["bisFor"] = "Prot Warrior, Ret Pally", ["gp"] = 0, ["note"] = ""},
  ["Bloodsoaked Coif"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodstained Greaves"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodstained Legplates"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodtinged Gloves"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Bloodtinged Kilt"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Cloak of Consumption"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = 0, ["note"] = ""},
  ["Cloak of the Hakkari Worshipers"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Fang of the Faceless"] = {["bisFor"] = "Hunter", ["gp"] = 0, ["note"] = ""},
  ["Fang of Venoxis"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Fiery Retributer"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Flowing Ritual Robes"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Foror's Eyepatch"] = {["bisFor"] = "Feral Druid", ["gp"] = 0, ["note"] = ""},
  ["Gloves of the Tormented"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Gri'lek's Blood"] = {["bisFor"] = "Holy Priest, Resto Druid (2), Sword Rogue (3), Dagger Rogue (3)", ["gp"] = 0, ["note"] = ""},
  ["Gri'lek's Carver"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Gri'lek's Grinder"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Gurubashi Dwarf Destroyer"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Hakkari Loa Cloak"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Halberd of Smiting"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Hazza'rah's Dream Thread"] = {["bisFor"] = "Holy Priest, Resto Druid (2), Sword Rogue (3), Dagger Rogue (3)", ["gp"] = 0, ["note"] = ""},
  ["Heart of Hakkar"] = {["bisFor"] = "Shadow Priest, Mage, Warlock, Holy Pally (2), Feral Druid (3)", ["gp"] = 0, ["note"] = ""},
  ["Hoodoo Hunting Bow"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Jeklik's Crusher"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Jeklik's Opaline Talisman"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Jin'do's Bag of Whammies"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Jin'do's Evil Eye"] = {["bisFor"] = "Resto Druid, Holy Pally, Holy Priest", ["gp"] = 0, ["note"] = ""},
  ["Jin'do's Hexxer"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Jin'do's Judgement"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Mandokir's Sting"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Mar'li's Eye"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Mar'li's Touch"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Might of the Tribe"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Nat Pagle's Broken Reel"] = {["bisFor"] = "Prot Warrior", ["gp"] = 0, ["note"] = "needed for 4 horsemen, all warriors need this"},
  ["Nat Pagle's Fish Terminator"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Overlord's Crimson Band"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Overlord's Embrace"] = {["bisFor"] = "Prot Warrior", ["gp"] = 0, ["note"] = ""},
  ["Overlord's Onyx Band"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Peacekeeper Boots"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Peacekeeper Gauntlets"] = {["bisFor"] = "Holy Pally", ["gp"] = 0, ["note"] = ""},
  ["Peacekeeper Leggings"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = "  "},
  ["Pitchfork of Madness"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Aegis"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Armsplint"] = {["bisFor"] = "Prot Warrior", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Bindings"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Girdle"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Idol"] = {["bisFor"] = "Prot Warrior, Resto Druid, Holy Pally, Holy Priest, Mage, Warlock, Hunter, Sword Rogue, Dagger Rogue", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Kossack"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Sash"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Shawl"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Stanchion"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primal Hakkari Tabbard"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primalist's Band"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Primalist's Seal"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Renataki's Soul Conduit"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Renataki's Tooth"] = {["bisFor"] = "Holy Priest, Resto Druid (2), Sword Rogue (3), Dagger Rogue (3)", ["gp"] = 0, ["note"] = ""},
  ["Ritualistic Leggards"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Runed Bloodstained Hauberk"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Sacrificial Gauntlets"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Seafury Boots"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Seafury Gauntlets"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Seafury Leggings"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Seal of Jin"] = {["bisFor"] = "Hunter", ["gp"] = 0, ["note"] = ""},
  ["Seal of the Gurubashi Berserker"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Soul Corrupter's Necklace"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Talisman of Protection"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["The Eye of Hakkar"] = {["bisFor"] = "Ret Pally, Fury Warrior", ["gp"] = 0, ["note"] = ""},
  ["The Hexxer's Cover"] = {["bisFor"] = "Shadow Priest", ["gp"] = 0, ["note"] = ""},
  ["Thekal's Grasp"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Thoughtblighter"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Tigule's Harpoon"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Touch of Chaos"] = {["bisFor"] = "Shadow Priest, Mage, Warlock", ["gp"] = 0, ["note"] = ""},
  ["Warblade of the Hakkari"] = {["bisFor"] = "Prot Warrior, Sword Rogue (2)", ["gp"] = 0, ["note"] = "set is BIS for fury prot warriors without Thunderfury (PROT with TF has no priority on either)"},
  ["Warblade of the Hakkari"] = {["bisFor"] = "Prot Warrior, Hunter (2)", ["gp"] = 0, ["note"] = "set is BIS for fury prot warriors without Thunderfury (PROT with TF has no priority on either)"},
  ["Will of Arlokk"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Wushoolay's Mane"] = {["bisFor"] = "Holy Priest, Resto Druid (2), Sword Rogue (3), Dagger Rogue (3)", ["gp"] = 0, ["note"] = ""},
  ["Wushoolay's Poker"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zanzil's Band"] = {["bisFor"] = "Warlock", ["gp"] = 0, ["note"] = ""},
  ["Zanzil's Seal"] = {["bisFor"] = "Warlock", ["gp"] = 0, ["note"] = ""},
  ["Zin'rokh, Destroyer of Worlds)"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zulian Defender"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zulian Headdress"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zulian Scepter of Rites"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zulian Slicer"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zulian Stone Axe"] = {["bisFor"] = "", ["gp"] = 0, ["note"] = ""},
  ["Zulian Tigerhide Cloak"] = {["bisFor"] = "Prot Warrior, Fury Warrior (2), Hunter (3)", ["gp"] = 0, ["note"] = ""}
}
